on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write  # Permite criar e enviar tags ao repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Garante que todas as tags sejam buscadas

    # Configura o .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Obtém a última tag com o maior número de versão e gera a próxima
    - name: Get latest tag and prepare versions
      id: version
      run: |
        # Obtém todas as tags e ordena semanticamente
        TAG=$(git tag | sort -V | tail -n 1)
        if [ -z "$TAG" ]; then
          TAG="v0.0.0"
        fi
        echo "Latest tag: $TAG"

        # Remove o prefixo "v" e incrementa a versão
        VERSION=${TAG#v}
        MAJOR=$(echo $VERSION | awk -F. '{print $1}')
        MINOR=$(echo $VERSION | awk -F. '{print $2}')
        PATCH=$(echo $VERSION | awk -F. '{print $3}')

        # Incrementa o PATCH ou ajusta o MINOR/MAJOR conforme necessário
        if [ "$PATCH" -eq 9 ]; then
          PATCH=0
          MINOR=$((MINOR + 1))
        else
          PATCH=$((PATCH + 1))
        fi

        if [ "$MINOR" -eq 10 ]; then
          MINOR=0
          MAJOR=$((MAJOR + 1))
        fi

        # Define as novas versões
        NEW_VERSION="v$MAJOR.$MINOR.$PATCH"  # Com prefixo "v"
        CLEAN_VERSION="$MAJOR.$MINOR.$PATCH" # Sem prefixo "v"

        echo "New version: $NEW_VERSION"
        echo "Clean version: $CLEAN_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV

    # Restaura as dependências do projeto
    - name: Restore dependencies
      run: dotnet restore

    # Compila o projeto
    - name: Build solution
      run: dotnet build --configuration Release

    # Verifica a formatação do código
    - name: Format code
      run: dotnet format ./DotNetStarter.sln

    # Empacota o projeto para NuGet
    - name: Pack NuGet Package
      run: dotnet pack DotNetStarter/DotNetStarter.CLI.csproj --configuration Release -o ./nupkg -p:PackageVersion=${{ env.NEW_VERSION#v }}

    # Lista os pacotes gerados (para depuração)
    - name: List generated packages
      run: ls -l ./nupkg

    # Publica no NuGet
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/DotNetStarter.CLI.${{ env.NEW_VERSION }}.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        
    # Cria e faz push de uma nova tag no repositório
    - name: Create and push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating and pushing tag: ${{ env.NEW_VERSION }}"
        git tag ${{ env.NEW_VERSION }}
        git push origin ${{ env.NEW_VERSION }}
